### ISSUE TITLE
前端没打字机效果

### ISSUE THREAD

**Issue by rhymed-liu** [WenJing95/chatgpt-web#1]
在本地测试前端没有打字机效果,原版的是可以的,请教下是哪里设置不对吗

**Comment by WenJing95** [comment]
是有这个问题，我在处理啦

**Comment by rhymed-liu** [comment]
期待这个问题的解决,node版本看不懂

**Comment by rhymed-liu** [comment]
我不是很看得懂python,但是我稍微了解了一下,打断点测试的时候发现yield并没有处于循环中,也就不会生效.我尝试如下修改就实现了打字机效果了
![image](https://user-images.githubusercontent.com/37588640/224631979-50277cd5-8276-40d6-9658-b0ed5ecf190c.png)

**Comment by WenJing95** [comment]
牛逼！感谢
