### ISSUE TITLE
前端页面-无法显示回复的文字

### ISSUE THREAD

**Issue by ipengyo** [WenJing95/chatgpt-web#10]
代码是： commit 91bd9a9686dd842512326dfd6001ce54b1e55fe8

表现如下：
从网络请求中时看到有数据返回的，但是前端没有把内容展示上去，看控制台是有报错的。

![image](https://user-images.githubusercontent.com/9323722/225799186-f00ab133-91a3-4624-928e-d37cd00e81d0.png)

![image](https://user-images.githubusercontent.com/9323722/225799287-d440fbd3-daa2-4113-a174-00ca01004dfc.png)

```
commons.js:formatted:47949 Channel: Error in handleResponse UNK/SW_UNREACHABLE isLogsEnabled null
_handleResponsePromise @ commons.js:formatted:47949
（匿名） @ commons.js:formatted:47764
2commons.js:formatted:47949 Channel: Error in handleResponse UNK/SW_UNREACHABLE options getValues
_handleResponsePromise @ commons.js:formatted:47949
（匿名） @ commons.js:formatted:47764
commons.js:formatted:47949 Channel: Error in handleResponse UNK/SW_UNREACHABLE contextMenu createContextMenu
_handleResponsePromise @ commons.js:formatted:47949
（匿名） @ commons.js:formatted:47764
commons.js:formatted:47949 Channel: Error in handleResponse UNK/SW_UNREACHABLE tabClipper initCompleted
_handleResponsePromise @ commons.js:formatted:47949
（匿名） @ commons.js:formatted:47764
2commons.js:formatted:47949 Channel: Error in handleResponse UNK/SW_UNREACHABLE options getValue
_handleResponsePromise @ commons.js:formatted:47949
（匿名） @ commons.js:formatted:47764
7commons.js:formatted:121945 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
fromGeneric @ commons.js:formatted:121945
fromAny @ commons.js:formatted:121930
_handleResponsePromise @ commons.js:formatted:47948
（匿名） @ commons.js:formatted:47764
commons.js:formatted:47949 Channel: Error in handleResponse UNK/SW_UNREACHABLE contextMenu createContextMenu
_handleResponsePromise @ commons.js:formatted:47949
（匿名） @ commons.js:formatted:47764
commons.js:formatted:47949 Channel: Error in handleResponse UNK/SW_UNREACHABLE tabClipper checkBackgroundStatus
_handleResponsePromise @ commons.js:formatted:47949
（匿名） @ commons.js:formatted:47764
commons.js:formatted:121945 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
fromGeneric @ commons.js:formatted:121945
fromAny @ commons.js:formatted:121930
_handleResponsePromise @ commons.js:formatted:47948
（匿名） @ commons.js:formatted:47764
commons.js:formatted:47949 Channel: Error in handleResponse UNK/SW_UNREACHABLE contextMenu createContextMenu
_handleResponsePromise @ commons.js:formatted:47949
（匿名） @ commons.js:formatted:47764
commons.js:formatted:121945 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
fromGeneric @ commons.js:formatted:121945
fromAny @ commons.js:formatted:121930
_handleResponsePromise @ commons.js:formatted:47948
（匿名） @ commons.js:formatted:47764
commons.js:formatted:47949 Channel: Error in handleResponse UNK/SW_UNREACHABLE contextMenu createContextMenu
_handleResponsePromise @ commons.js:formatted:47949
（匿名） @ commons.js:formatted:47764
commons.js:formatted:121945 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
fromGeneric @ commons.js:formatted:121945
fromAny @ commons.js:formatted:121930
_handleResponsePromise @ commons.js:formatted:47948
（匿名） @ commons.js:formatted:47764
commons.js:formatted:47949 Channel: Error in handleResponse UNK/SW_UNREACHABLE broadcastEventToTab clipper_state_changed
_handleResponsePromise @ commons.js:formatted:47949
（匿名） @ commons.js:formatted:47764
Promise.catch（异步）
_sendMessageToExtension @ commons.js:formatted:47758
sendToExtension @ commons.js:formatted:47631
（匿名） @ commons.js:formatted:106945
Promise.then（异步）
ie @ commons.js:formatted:106943
（匿名） @ commons.js:formatted:107569
commons.js:formatted:121945 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
fromGeneric @ commons.js:formatted:121945
fromAny @ commons.js:formatted:121930
_handleResponsePromise @ commons.js:formatted:47948
（匿名） @ commons.js:formatted:47764
Promise.catch（异步）
_sendMessageToExtension @ commons.js:formatted:47758
sendToExtension @ commons.js:formatted:47631
（匿名） @ commons.js:formatted:106945
Promise.then（异步）
ie @ commons.js:formatted:106943
（匿名） @ commons.js:formatted:107569
commons.js:formatted:47949 Channel: Error in handleResponse UNK/SW_UNREACHABLE contextMenu createContextMenu
_handleResponsePromise @ commons.js:formatted:47949
（匿名） @ commons.js:formatted:47764
Promise.catch（异步）
_sendMessageToExtension @ commons.js:formatted:47758
sendToExtension @ commons.js:formatted:47631
send @ commons.js:formatted:106782
listener @ commons.js:formatted:106809
commons.js:formatted:121945 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
```

**Comment by WenJing95** [comment]
你的开发环境网络有问题，我帮你搜索了一下，有以下解决方法供参考
1. 清理浏览器缓存、重启浏览器
2. [重启电脑](https://blog.csdn.net/threewhisky/article/details/89156872)
3. 确认你的前端代码，是不是不小心输入了一些字符，破坏了代码的完整性
4. 删除node_modules并重新安装
5. [删除有问题的chrome插件(如Evernote Web Clipper)](https://stackoverflow.com/questions/75722844/how-to-handle-reactjs-error-that-happens-on-page-load)，或更换浏览器

**Comment by ipengyo** [comment]
> 你的开发环境网络有问题，我帮你搜索了一下，有以下解决方法供参考
> 
> 1. 清理浏览器缓存、重启浏览器
> 2. [重启电脑](https://blog.csdn.net/threewhisky/article/details/89156872)
> 3. 确认你的前端代码，是不是不小心输入了一些字符，破坏了代码的完整性
> 4. 删除node_modules并重新安装
> 5. [删除有问题的chrome插件(如Evernote Web Clipper)](https://stackoverflow.com/questions/75722844/how-to-handle-reactjs-error-that-happens-on-page-load)，或更换浏览器

谢谢你，经过我debug排查，是如下这段代码有问题：
![image](https://user-images.githubusercontent.com/9323722/225805310-cb9fec9e-26ee-4eee-94e8-e8c75d00ff66.png)
![image](https://user-images.githubusercontent.com/9323722/225805349-09f141d5-a79e-4577-a078-6928dec3d18a.png)

**Comment by ipengyo** [comment]
@WenJing95 

wenjing 我看此提交https://github.com/WenJing95/chatgpt-web/commit/518657d7873ed55a42438b19dfde20ea213f7331 有将\n的分割换成"data: "的分割，请问这个是为了什么，我从目前的network中看到 我目前的服务端返回值是没有"data:" 分割 返回的

**Comment by WenJing95** [comment]
因为服务器端返回内容的方式改成了SSE (在这次commit 0995afb)，你需要更新服务器端程序的代码

**Comment by ipengyo** [comment]
> 因为服务器端返回内容的方式改成了SSE (在这次commit [0995afb](https://github.com/WenJing95/chatgpt-web/commit/0995afbff32b74e61c4f937820ffdc6356cd9ca1))，SSE协议的数据内容常用 `data:` 开头，你需要更新服务器端程序的代码

我是更新的最新的代码，今天上午刚拉的。。。。
也是有这段代码的，所以很奇怪

![image](https://user-images.githubusercontent.com/9323722/225808108-ba2360ce-57ce-4a00-b8ce-2a4f132d9b0f.png)

**Comment by WenJing95** [comment]
你打印信息的代码是在 `responseText = removeDataPrefix(responseText)` 这一行之后。前缀被这个函数去掉了，然后你才打印的，所以你看不到前缀

**Comment by WenJing95** [comment]
> > 你的开发环境网络有问题，我帮你搜索了一下，有以下解决方法供参考
> > 
> > 1. 清理浏览器缓存、重启浏览器
> > 2. [重启电脑](https://blog.csdn.net/threewhisky/article/details/89156872)
> > 3. 确认你的前端代码，是不是不小心输入了一些字符，破坏了代码的完整性
> > 4. 删除node_modules并重新安装
> > 5. [删除有问题的chrome插件(如Evernote Web Clipper)](https://stackoverflow.com/questions/75722844/how-to-handle-reactjs-error-that-happens-on-page-load)，或更换浏览器
> 
> 谢谢你，经过我debug排查，是如下这段代码有问题： ![image](https://user-images.githubusercontent.com/9323722/225805310-cb9fec9e-26ee-4eee-94e8-e8c75d00ff66.png) ![image](https://user-images.githubusercontent.com/9323722/225805349-09f141d5-a79e-4577-a078-6928dec3d18a.png)

这里catch的目的是，有时候前端收到回答内容不符合json格式，需要将这条信息忽略掉，所以不用管这里的异常信息

**Comment by ipengyo** [comment]
> 你打印信息的代码是在 `responseText = removeDataPrefix(responseText)` 这一行之后。前缀被这个函数去掉了，然后你才打印的，所以你看不到前缀

我是从network上面看返回的内容，好像是没有的。

EventSourceResponse

**Comment by ipengyo** [comment]
![image](https://user-images.githubusercontent.com/9323722/225810737-c485560c-f163-4226-8aa0-f944d416c247.png)

**Comment by ipengyo** [comment]
> > > 你的开发环境网络有问题，我帮你搜索了一下，有以下解决方法供参考
> > > 
> > > 1. 清理浏览器缓存、重启浏览器
> > > 2. [重启电脑](https://blog.csdn.net/threewhisky/article/details/89156872)
> > > 3. 确认你的前端代码，是不是不小心输入了一些字符，破坏了代码的完整性
> > > 4. 删除node_modules并重新安装
> > > 5. [删除有问题的chrome插件(如Evernote Web Clipper)](https://stackoverflow.com/questions/75722844/how-to-handle-reactjs-error-that-happens-on-page-load)，或更换浏览器
> > 
> > 
> > 谢谢你，经过我debug排查，是如下这段代码有问题： ![image](https://user-images.githubusercontent.com/9323722/225805310-cb9fec9e-26ee-4eee-94e8-e8c75d00ff66.png) ![image](https://user-images.githubusercontent.com/9323722/225805349-09f141d5-a79e-4577-a078-6928dec3d18a.png)
> 
> 这里catch的目的是，有时候前端收到回答内容不符合json格式，需要将这条信息忽略掉，所以不用管这里的异常信息

好的。这里最后有个日志记录，不然报错了不好找问题。。

**Comment by ipengyo** [comment]
经过查询：
![image](https://user-images.githubusercontent.com/9323722/225811309-3499317d-64f9-4bfb-8e5c-479e032814bd.png)

我们目前返回的不是标准格式。

**Comment by WenJing95** [comment]
![image](https://user-images.githubusercontent.com/126436871/225811856-3e291da9-adb4-40a0-80c1-917fe21d533c.png)
是有点奇怪，我这里换了3个平台测试，看起来都是标准格式。你`python`和`sse-starlette`的版本，还有浏览器版本是？

**Comment by WenJing95** [comment]
![image](https://user-images.githubusercontent.com/126436871/225813002-c17dbde4-03d9-457d-99e3-ba52c0a3b22d.png)
可能是浏览器的问题，我更新个通用的版本吧

**Comment by ipengyo** [comment]
> ![image](https://user-images.githubusercontent.com/126436871/225813002-c17dbde4-03d9-457d-99e3-ba52c0a3b22d.png) 可能是浏览器的问题，我更新个通用的版本吧

好的 辛苦大佬；

**Comment by ipengyo** [comment]
> 
ServerSentEvent = 
```
__all__ = ["ServerSentEvent", "EventSourceResponse"]
__version__ = "1.3.3"
```

python
```
Python 3.10.10
```

浏览器
```
chrome: 版本 104.0.5112.102（正式版本） （64 位）

```

**Comment by ipengyo** [comment]
@WenJing95 

非常抱歉，我找到原因了；数据不一致的问题是因为我开了原版的程序没有关，而开启了本程序的前端代理请求是打到原版的后端去的，所以导致了网络通的，但是内容不一致的情况。

不好意思给你造成困扰了！！
