### ISSUE TITLE
你考虑将主线项目中的一些功能merge 到你现在的项目中去吗？

### ISSUE THREAD

**Issue by JinhuW** [WenJing95/chatgpt-web#14]

**Comment by WenJing95** [comment]
我一直都会跟随主项目更新的，但是我会选择性舍弃一些功能，因为我希望让这个项目尽量简单、傻瓜一点，不那么geek。

如果你有非常专业的需求，欢迎你fork之后自行开发，我也会关注你的进展，互相学习

**Comment by JinhuW** [comment]
好奇 你的图片输出是怎么做到的？
