### ISSUE TITLE
请问可以添加权限验证吗？

### ISSUE THREAD

**Issue by fzucs** [WenJing95/chatgpt-web#16]
想搭来给朋友们玩一玩，但是又怕被搜到，导致api滥用。所以想问能不能像主项目一样加个权限验证。感谢您为我们小白用户考虑！ps:你们两个项目都各有很棒的功能，要是能合在一起就好了。

**Comment by WenJing95** [comment]
暂时没打算，以后可能会加。现在你可以用以下方式实现这个需求

1. 给网站添加path，例如将 `your.site.com` 改成 `your.site.com/xxxxx` 这样的地址，`xxxxx` 这部分稍微设置复杂一点就行了。这样的好处是能防住一些网络上的探测，而且你朋友不需要记住密码，只要保存链接就行了。缺点是这个方案做不到100%的防御
2. 在nginx配置中使用 `auth_basic` 配置身份验证，配置好之后记得关闭服务器端口的公网访问权限，只允许nginx代理访问
3. 使用[主项目](https://github.com/Chanzhaoyu/chatgpt-web)，他这个就是最好的


目前对于不在it行业的亲友来说，chatgpt还算陌生的。所以我的项目倾向于不设障碍 (大部分人看到密码框就放弃了，如果你还想让他记一个复杂密码，那就更没可能了)
这样做的目的是想让身边人都能尝尝鲜，人嘛见过了好东西，就不会再被那啥骗得团团转。等chatgpt被培养成了刚需，再加这个验证也不迟吧
