### ISSUE TITLE
希望能增加支持GPT4.0

### ISSUE THREAD

**Issue by expfukck** [WenJing95/chatgpt-web#18]
希望能增加个!

**Comment by expfukck** [comment]
不支持反向代理地址吗?

**Comment by WenJing95** [comment]
> 希望能增加个!

官方开放接口之后会添加支持

**Comment by expfukck** [comment]
> > 不支持反向代理地址吗?
> 
> 不支持，使用反向代理会增加信息泄露和封号风险。建议自建正向代理

说错了 是api代理  能支持自定义API代理吗!

**Comment by WenJing95** [comment]
> > > 不支持反向代理地址吗?
> > 
> > 
> > 不支持，使用反向代理会增加信息泄露和封号风险。建议自建正向代理
> 
> 说错了 是api代理 能支持自定义API代理吗!

支持，文档里搜 `socks_proxy` 有示例

**Comment by WenJing95** [comment]
> > > > > 不支持反向代理地址吗?
> > > > 
> > > > 
> > > > 不支持，使用反向代理会增加信息泄露和封号风险。建议自建正向代理
> > > 
> > > 
> > > 说错了 是api代理 能支持自定义API代理吗!
> > 
> > 
> > 支持，文档里搜 `socks_proxy` 有示例
> 
> 为什么一直是访问OpenAI GPT API出错，请稍后再试

检查你的服务端运行日志，里面有详细信息

**Comment by expfukck** [comment]
> > > > > > 不支持反向代理地址吗?
> > > > > 
> > > > > 
> > > > > 不支持，使用反向代理会增加信息泄露和封号风险。建议自建正向代理
> > > > 
> > > > 
> > > > 说错了 是api代理 能支持自定义API代理吗!
> > > 
> > > 
> > > 支持，文档里搜 `socks_proxy` 有示例
> > 
> > 
> > 为什么一直是访问OpenAI GPT API出错，请稍后再试
> 
> 检查你的服务端运行日志，里面有详细信息

找到问题了 是API代理访问不了 能增加支持OPENAI_API_BASE 和访问秘钥吗

**Comment by WenJing95** [comment]
看看这个有用吗 #19

**Comment by expfukck** [comment]
> 看看这个有用吗 #19

试了 我不加OPENAI_API_BASE  不动任何文件 用Dockerfile 生成镜像 然后我docker-compose  容器一直是失败的 请你检测下! 搞了一下午 就是没成功..直接用你镜像docker-compose 就成功的

**Comment by WenJing95** [comment]
我确定这个方法可以正常启动，并且设置api_base，以下是测试截图：

`Dockerfile`:
![image](https://user-images.githubusercontent.com/126436871/227200035-18ba23dc-42b0-4357-a418-a0cc028df020.png)
`main.py`
![image](https://user-images.githubusercontent.com/126436871/227199505-3479c25d-f9b0-4186-8444-58bf08844903.png)
`docker-compose启动日志`
![image](https://user-images.githubusercontent.com/126436871/227199342-a5d44b4f-4374-4b59-a79a-8a3fe81652e1.png)
