### ISSUE TITLE
BUG: 线上运行python程序CPU100%，无法处理请求

### ISSUE THREAD

**Issue by ipengyo** [WenJing95/chatgpt-web#21]
![VSY(DWXZGD2ZV$72B(FI 7L](https://user-images.githubusercontent.com/9323722/227424597-77d96b42-b6ba-4785-a4cd-39327f9fd591.png)

原因：目前未知；
状态： 程序跑了5天之后就莫名其妙这样了，我重启后就正常了。
猜测： 可能是这个版本的代码没有网络Timeout机制，也许时间一长就累计起来了。 （下次遇到我一定要把堆栈记录下来）
代码版本：[ 36680b8918dd5fef7b96a4231785570c28c13599
](https://github.com/WenJing95/chatgpt-web/commit/b9cc546c2e76687df4becf79ebef744f6ce5e9af)

**Comment by WenJing95** [comment]
在 d34f760 尝试修复了
