### ISSUE TITLE
项目可以联网回复吗

### ISSUE THREAD

**Issue by wuzhijie0101** [WenJing95/chatgpt-web#22]
偶然看到评论可以联网回复的项目，觉得还不错。
[https://github.com/binjie09/chatgpt-web](url)
![微信截图_20230324153752](https://user-images.githubusercontent.com/126138070/227455708-a55e9538-0b8b-41d4-a50a-be7395ecfe3c.png)

**Comment by WenJing95** [comment]
可以研究看看。看起来有点像ChatGPT刚出的plugins
