### ISSUE TITLE
聊天记录没有同步，也没有在服务端保存

### ISSUE THREAD

**Issue by JokerQyou** [WenJing95/chatgpt-web#25]
README 中说：

> 可以“记住”更多的上下文：聊天记录保存在服务器端，不会因为网页端清理缓存而丢失上下文，影响回答质量

实际用两个浏览器访问，在A浏览器上聊天内容在B浏览器上不显示。在B浏览器中询问“我们刚才聊到哪了”，也回复说还没有聊天记录。所以这个功能具体是怎么用的？

**Comment by WenJing95** [comment]
需要在同一个会话中连续聊天
