### ISSUE TITLE
答案输出没有原版顺滑

### ISSUE THREAD

**Issue by talentyao** [WenJing95/chatgpt-web#8]
部署你这个版本发现答案是过段时间跳出一段，而原版会一个个字出来给人感响应很快。这个问题如果可以优化下就完美了

**Comment by WenJing95** [comment]
公网环境没有这个问题，可查看：  [在线演示](https://simplegpt.io)

在本地开发环境，确实有这个情况。现在已经观察到是因为后端通过sse响应的时候，并非是逐条返回数据，而是积攒了一批数据一起返回导致的。

问题应该出在后端框架或网络层，我尝试过一些方法都没能控制这个数据的返回频率，所以就暂时搁置了。后面有时间考虑在前端层面解决，或者换成websocket试试
